---

# check host role

- name: Validate hosts against desired cluster state
  hosts: all
  gather_facts: false
  vars:
    inventory:
      localhost:
        mons,osds

  tasks:
 
    - name: CEPH_CHECK_ROLE
      ceph_check_role:
        role: "{{ inventory[inventory_hostname] }}"
        mode: prod
        deployment: rpm
